### ISSUE TITLE
Bug using word without table

### ISSUE THREAD

**Issue by jerry0012000** [whiteS18/WordToHtml#1]
If I convert a docx file with table, the program runs correctly. However, if I convert a docx file without table, it crashes with the following error:

Exception in thread "main" org.apache.poi.xwpf.converter.core.XWPFConverterException: java.lang.IllegalStateException: Expecting one Styles document part, but found 0
	at org.apache.poi.xwpf.converter.xhtml.XHTMLConverter.convert(XHTMLConverter.java:77)
	at org.apache.poi.xwpf.converter.xhtml.XHTMLConverter.doConvert(XHTMLConverter.java:63)
	at org.apache.poi.xwpf.converter.xhtml.XHTMLConverter.doConvert(XHTMLConverter.java:38)
	at org.apache.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:45)
	at WordToHtml.WordToHtml.docToHtml(WordToHtml.java:80)
	at WordToHtml.WordToHtml.main(WordToHtml.java:38)
Caused by: java.lang.IllegalStateException: Expecting one Styles document part, but found 0
	at org.apache.poi.xwpf.usermodel.XWPFDocument.getStyle(XWPFDocument.java:461)
	at org.apache.poi.xwpf.converter.core.styles.XWPFStylesDocument.<init>(XWPFStylesDocument.java:190)
	at org.apache.poi.xwpf.converter.xhtml.internal.styles.CSSStylesDocument.<init>(CSSStylesDocument.java:100)
	at org.apache.poi.xwpf.converter.xhtml.internal.XHTMLMapper.createStylesDocument(XHTMLMapper.java:147)
	at org.apache.poi.xwpf.converter.core.XWPFDocumentVisitor.<init>(XWPFDocumentVisitor.java:159)
	at org.apache.poi.xwpf.converter.xhtml.internal.XHTMLMapper.<init>(XHTMLMapper.java:137)
	at org.apache.poi.xwpf.converter.xhtml.XHTMLConverter.convert(XHTMLConverter.java:72)
	... 5 more

Process finished with exit code 1

**Comment by whiteS18** [comment]
Hello, I tried to convert the docx documents with and without table on my computer, and the program can run successfully. If you can, please send me a copy of your document, and I will debug it.

[docx with table.docx](https://github.com/whiteS18/WordToHtml/files/4793596/docx.with.table.docx)
[docx without table.docx](https://github.com/whiteS18/WordToHtml/files/4793621/docx.with.table.docx)

**Comment by jerry0012000** [comment]
After more trying, I found that it's not the issue about tables. Some of my word documents are generated by apache POI, rather than created by Microsoft Word 2007.
[警告，这个文件有100万行.docx](https://github.com/whiteS18/WordToHtml/files/4795648/100.docx)

**Comment by whiteS18** [comment]
Sorry, I didn't test the documents generated by Apache poi. This program only tests Microsoft Word. In addition, 1 million pieces of data are too large, so it's not convenient to use word to transfer HTML

**Comment by jerry0012000** [comment]
This file is also generated by Apache POI, only one thousand lines, doesn't work either.
[警告，这个文件有0.1万行.docx](https://github.com/whiteS18/WordToHtml/files/4796796/0.1.docx)

**Comment by whiteS18** [comment]
It looks like you forgot to add styles when generating documents

**Comment by jerry0012000** [comment]
Maybe those are generated automatically when we use Microsoft Word, while POI doesn't do.

**Comment by whiteS18** [comment]
> Maybe those are generated automatically when we use Microsoft Word, while POI doesn't do.

yes ,like  style and picNumber
